# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.1'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', require: false
gem 'graphql'
gem 'graphql-rails_logger'
gem 'image_processing', '~> 1.2'
gem 'jwt'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'rails', '~> 7.0.2', '>= 7.0.2.3'
gem 'rails-i18n'
gem 'redis', '~> 4.0'
gem 'sqlite3', '~> 1.4'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'rspec-rails'
end

group :development do
  gem 'awesome_print'
  gem 'rbs_rails'
  gem 'rubocop'
  gem 'steep'
end

group :test do
  gem 'shoulda-matchers'
end
